import type { Metadata } from "next";
import { Jost, Playball } from "next/font/google";
import "./globals.css";

const jost = Jost({ subsets: ["latin"] });
const playball = Playball({
  subsets: ["latin"],
  variable: "--font-playball",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jost.className} ${playball.variable}`}>
        {children}
      </body>
      <div id="modal-container"></div>
    </html>
  );
}
